
name: User Story
description: Capture a user-centered requirement or feature
title: "[User Story]: "
labels: [user-story, needs-triage]
assignees: []
---

body:
  - type: markdown
    attributes:
      value: "## 🧑‍💻 User Story"

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: Write your user story in the format \"As a [type of user], I want [some goal] so that [some reason].\"
      placeholder: As a [user], I want [goal] so that [value/benefit].

  - type: markdown
    attributes:
      value: "---"

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define how you’ll know this user story is complete
      placeholder: |
        - Given [context]
        - When [event]
        - Then [outcome]

  - type: markdown
    attributes:
      value: "---"

  - type: input
    id: priority
    attributes:
      label: Priority
      description: Priority level (1 = High, 5 = Low)
      placeholder: 3

  - type: input
    id: value_area
    attributes:
      label: Value Area
